# Generated by Django 3.2.9 on 2021-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.Address'),
        ),
    ]
