# Generated by Django 3.2.9 on 2022-01-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_is_main'),
        ('food_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='main branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
