# Generated by Django 3.2.9 on 2021-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='meal_category',
            field=models.ManyToManyField(blank=True, related_name='foods', to='food_ordering.MealCategory'),
        ),
    ]
