# Generated by Django 3.2.9 on 2022-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='main address'),
        ),
    ]
