# Generated by Django 3.2.9 on 2022-01-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220106_2131'),
        ('food_ordering', '0003_auto_20220106_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
